// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Gateserver2000.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Gate {

  /// <summary>Holder for reflection information generated from Gateserver2000.proto</summary>
  public static partial class Gateserver2000Reflection {

    #region Descriptor
    /// <summary>File descriptor for Gateserver2000.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static Gateserver2000Reflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRHYXRlc2VydmVyMjAwMC5wcm90byLEAgoKR2F0ZXNlcnZlchIPCgdsdWFf",
            "dXJsGAsgASgJEhMKC3JlZ2lvbl9uYW1lGA0gASgJEhcKD2V4X3Jlc291cmNl",
            "X3VybBgJIAEoCRIVCgxpZml4X3ZlcnNpb24YpAsgASgJEhgKEGFzc2V0X2J1",
            "bmRsZV91cmwYASABKAkSDAoEcG9ydBgHIAEoDRIKCgJpcBgMIAEoCRIMCgNt",
            "c2cYtAggASgJEhEKCGlmaXhfdXJsGIwBIAEoCRIYCg9tZGtfcmVzX3ZlcnNp",
            "b24YsAsgASgJEhoKEWNsaWVudF9zZWNyZXRfa2V5GM8EIAEoCRIMCgR1bmsx",
            "GAQgASgIEgwKBHVuazIYCCABKAgSDAoEdW5rMxhCIAEoCBINCgR1bms0GKcE",
            "IAEoCBINCgR1bms1GKEHIAEoCBINCgR1bms2GNMHIAEoCEIcChNlbXUubHVu",
            "YXJjb3JlLnByb3RvqgIER2F0ZWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Gate.Gateserver), global::Gate.Gateserver.Parser, new[]{ "LuaUrl", "RegionName", "ExResourceUrl", "IfixVersion", "AssetBundleUrl", "Port", "Ip", "Msg", "IfixUrl", "MdkResVersion", "ClientSecretKey", "Unk1", "Unk2", "Unk3", "Unk4", "Unk5", "Unk6" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Gateserver : pb::IMessage<Gateserver>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Gateserver> _parser = new pb::MessageParser<Gateserver>(() => new Gateserver());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Gateserver> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Gate.Gateserver2000Reflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Gateserver() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Gateserver(Gateserver other) : this() {
      luaUrl_ = other.luaUrl_;
      regionName_ = other.regionName_;
      exResourceUrl_ = other.exResourceUrl_;
      ifixVersion_ = other.ifixVersion_;
      assetBundleUrl_ = other.assetBundleUrl_;
      port_ = other.port_;
      ip_ = other.ip_;
      msg_ = other.msg_;
      ifixUrl_ = other.ifixUrl_;
      mdkResVersion_ = other.mdkResVersion_;
      clientSecretKey_ = other.clientSecretKey_;
      unk1_ = other.unk1_;
      unk2_ = other.unk2_;
      unk3_ = other.unk3_;
      unk4_ = other.unk4_;
      unk5_ = other.unk5_;
      unk6_ = other.unk6_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Gateserver Clone() {
      return new Gateserver(this);
    }

    /// <summary>Field number for the "lua_url" field.</summary>
    public const int LuaUrlFieldNumber = 11;
    private string luaUrl_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string LuaUrl {
      get { return luaUrl_; }
      set {
        luaUrl_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "region_name" field.</summary>
    public const int RegionNameFieldNumber = 13;
    private string regionName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string RegionName {
      get { return regionName_; }
      set {
        regionName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ex_resource_url" field.</summary>
    public const int ExResourceUrlFieldNumber = 9;
    private string exResourceUrl_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ExResourceUrl {
      get { return exResourceUrl_; }
      set {
        exResourceUrl_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ifix_version" field.</summary>
    public const int IfixVersionFieldNumber = 1444;
    private string ifixVersion_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string IfixVersion {
      get { return ifixVersion_; }
      set {
        ifixVersion_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "asset_bundle_url" field.</summary>
    public const int AssetBundleUrlFieldNumber = 1;
    private string assetBundleUrl_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string AssetBundleUrl {
      get { return assetBundleUrl_; }
      set {
        assetBundleUrl_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "port" field.</summary>
    public const int PortFieldNumber = 7;
    private uint port_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Port {
      get { return port_; }
      set {
        port_ = value;
      }
    }

    /// <summary>Field number for the "ip" field.</summary>
    public const int IpFieldNumber = 12;
    private string ip_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Ip {
      get { return ip_; }
      set {
        ip_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "msg" field.</summary>
    public const int MsgFieldNumber = 1076;
    private string msg_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Msg {
      get { return msg_; }
      set {
        msg_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ifix_url" field.</summary>
    public const int IfixUrlFieldNumber = 140;
    private string ifixUrl_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string IfixUrl {
      get { return ifixUrl_; }
      set {
        ifixUrl_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "mdk_res_version" field.</summary>
    public const int MdkResVersionFieldNumber = 1456;
    private string mdkResVersion_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string MdkResVersion {
      get { return mdkResVersion_; }
      set {
        mdkResVersion_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "client_secret_key" field.</summary>
    public const int ClientSecretKeyFieldNumber = 591;
    private string clientSecretKey_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ClientSecretKey {
      get { return clientSecretKey_; }
      set {
        clientSecretKey_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "unk1" field.</summary>
    public const int Unk1FieldNumber = 4;
    private bool unk1_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Unk1 {
      get { return unk1_; }
      set {
        unk1_ = value;
      }
    }

    /// <summary>Field number for the "unk2" field.</summary>
    public const int Unk2FieldNumber = 8;
    private bool unk2_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Unk2 {
      get { return unk2_; }
      set {
        unk2_ = value;
      }
    }

    /// <summary>Field number for the "unk3" field.</summary>
    public const int Unk3FieldNumber = 66;
    private bool unk3_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Unk3 {
      get { return unk3_; }
      set {
        unk3_ = value;
      }
    }

    /// <summary>Field number for the "unk4" field.</summary>
    public const int Unk4FieldNumber = 551;
    private bool unk4_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Unk4 {
      get { return unk4_; }
      set {
        unk4_ = value;
      }
    }

    /// <summary>Field number for the "unk5" field.</summary>
    public const int Unk5FieldNumber = 929;
    private bool unk5_;
    /// <summary>
    ///bool unk5 = 646;
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Unk5 {
      get { return unk5_; }
      set {
        unk5_ = value;
      }
    }

    /// <summary>Field number for the "unk6" field.</summary>
    public const int Unk6FieldNumber = 979;
    private bool unk6_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Unk6 {
      get { return unk6_; }
      set {
        unk6_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Gateserver);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Gateserver other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (LuaUrl != other.LuaUrl) return false;
      if (RegionName != other.RegionName) return false;
      if (ExResourceUrl != other.ExResourceUrl) return false;
      if (IfixVersion != other.IfixVersion) return false;
      if (AssetBundleUrl != other.AssetBundleUrl) return false;
      if (Port != other.Port) return false;
      if (Ip != other.Ip) return false;
      if (Msg != other.Msg) return false;
      if (IfixUrl != other.IfixUrl) return false;
      if (MdkResVersion != other.MdkResVersion) return false;
      if (ClientSecretKey != other.ClientSecretKey) return false;
      if (Unk1 != other.Unk1) return false;
      if (Unk2 != other.Unk2) return false;
      if (Unk3 != other.Unk3) return false;
      if (Unk4 != other.Unk4) return false;
      if (Unk5 != other.Unk5) return false;
      if (Unk6 != other.Unk6) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (LuaUrl.Length != 0) hash ^= LuaUrl.GetHashCode();
      if (RegionName.Length != 0) hash ^= RegionName.GetHashCode();
      if (ExResourceUrl.Length != 0) hash ^= ExResourceUrl.GetHashCode();
      if (IfixVersion.Length != 0) hash ^= IfixVersion.GetHashCode();
      if (AssetBundleUrl.Length != 0) hash ^= AssetBundleUrl.GetHashCode();
      if (Port != 0) hash ^= Port.GetHashCode();
      if (Ip.Length != 0) hash ^= Ip.GetHashCode();
      if (Msg.Length != 0) hash ^= Msg.GetHashCode();
      if (IfixUrl.Length != 0) hash ^= IfixUrl.GetHashCode();
      if (MdkResVersion.Length != 0) hash ^= MdkResVersion.GetHashCode();
      if (ClientSecretKey.Length != 0) hash ^= ClientSecretKey.GetHashCode();
      if (Unk1 != false) hash ^= Unk1.GetHashCode();
      if (Unk2 != false) hash ^= Unk2.GetHashCode();
      if (Unk3 != false) hash ^= Unk3.GetHashCode();
      if (Unk4 != false) hash ^= Unk4.GetHashCode();
      if (Unk5 != false) hash ^= Unk5.GetHashCode();
      if (Unk6 != false) hash ^= Unk6.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (AssetBundleUrl.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(AssetBundleUrl);
      }
      if (Unk1 != false) {
        output.WriteRawTag(32);
        output.WriteBool(Unk1);
      }
      if (Port != 0) {
        output.WriteRawTag(56);
        output.WriteUInt32(Port);
      }
      if (Unk2 != false) {
        output.WriteRawTag(64);
        output.WriteBool(Unk2);
      }
      if (ExResourceUrl.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(ExResourceUrl);
      }
      if (LuaUrl.Length != 0) {
        output.WriteRawTag(90);
        output.WriteString(LuaUrl);
      }
      if (Ip.Length != 0) {
        output.WriteRawTag(98);
        output.WriteString(Ip);
      }
      if (RegionName.Length != 0) {
        output.WriteRawTag(106);
        output.WriteString(RegionName);
      }
      if (Unk3 != false) {
        output.WriteRawTag(144, 4);
        output.WriteBool(Unk3);
      }
      if (IfixUrl.Length != 0) {
        output.WriteRawTag(226, 8);
        output.WriteString(IfixUrl);
      }
      if (Unk4 != false) {
        output.WriteRawTag(184, 34);
        output.WriteBool(Unk4);
      }
      if (ClientSecretKey.Length != 0) {
        output.WriteRawTag(250, 36);
        output.WriteString(ClientSecretKey);
      }
      if (Unk5 != false) {
        output.WriteRawTag(136, 58);
        output.WriteBool(Unk5);
      }
      if (Unk6 != false) {
        output.WriteRawTag(152, 61);
        output.WriteBool(Unk6);
      }
      if (Msg.Length != 0) {
        output.WriteRawTag(162, 67);
        output.WriteString(Msg);
      }
      if (IfixVersion.Length != 0) {
        output.WriteRawTag(162, 90);
        output.WriteString(IfixVersion);
      }
      if (MdkResVersion.Length != 0) {
        output.WriteRawTag(130, 91);
        output.WriteString(MdkResVersion);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (AssetBundleUrl.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(AssetBundleUrl);
      }
      if (Unk1 != false) {
        output.WriteRawTag(32);
        output.WriteBool(Unk1);
      }
      if (Port != 0) {
        output.WriteRawTag(56);
        output.WriteUInt32(Port);
      }
      if (Unk2 != false) {
        output.WriteRawTag(64);
        output.WriteBool(Unk2);
      }
      if (ExResourceUrl.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(ExResourceUrl);
      }
      if (LuaUrl.Length != 0) {
        output.WriteRawTag(90);
        output.WriteString(LuaUrl);
      }
      if (Ip.Length != 0) {
        output.WriteRawTag(98);
        output.WriteString(Ip);
      }
      if (RegionName.Length != 0) {
        output.WriteRawTag(106);
        output.WriteString(RegionName);
      }
      if (Unk3 != false) {
        output.WriteRawTag(144, 4);
        output.WriteBool(Unk3);
      }
      if (IfixUrl.Length != 0) {
        output.WriteRawTag(226, 8);
        output.WriteString(IfixUrl);
      }
      if (Unk4 != false) {
        output.WriteRawTag(184, 34);
        output.WriteBool(Unk4);
      }
      if (ClientSecretKey.Length != 0) {
        output.WriteRawTag(250, 36);
        output.WriteString(ClientSecretKey);
      }
      if (Unk5 != false) {
        output.WriteRawTag(136, 58);
        output.WriteBool(Unk5);
      }
      if (Unk6 != false) {
        output.WriteRawTag(152, 61);
        output.WriteBool(Unk6);
      }
      if (Msg.Length != 0) {
        output.WriteRawTag(162, 67);
        output.WriteString(Msg);
      }
      if (IfixVersion.Length != 0) {
        output.WriteRawTag(162, 90);
        output.WriteString(IfixVersion);
      }
      if (MdkResVersion.Length != 0) {
        output.WriteRawTag(130, 91);
        output.WriteString(MdkResVersion);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (LuaUrl.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(LuaUrl);
      }
      if (RegionName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(RegionName);
      }
      if (ExResourceUrl.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ExResourceUrl);
      }
      if (IfixVersion.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(IfixVersion);
      }
      if (AssetBundleUrl.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AssetBundleUrl);
      }
      if (Port != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Port);
      }
      if (Ip.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Ip);
      }
      if (Msg.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(Msg);
      }
      if (IfixUrl.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(IfixUrl);
      }
      if (MdkResVersion.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(MdkResVersion);
      }
      if (ClientSecretKey.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(ClientSecretKey);
      }
      if (Unk1 != false) {
        size += 1 + 1;
      }
      if (Unk2 != false) {
        size += 1 + 1;
      }
      if (Unk3 != false) {
        size += 2 + 1;
      }
      if (Unk4 != false) {
        size += 2 + 1;
      }
      if (Unk5 != false) {
        size += 2 + 1;
      }
      if (Unk6 != false) {
        size += 2 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Gateserver other) {
      if (other == null) {
        return;
      }
      if (other.LuaUrl.Length != 0) {
        LuaUrl = other.LuaUrl;
      }
      if (other.RegionName.Length != 0) {
        RegionName = other.RegionName;
      }
      if (other.ExResourceUrl.Length != 0) {
        ExResourceUrl = other.ExResourceUrl;
      }
      if (other.IfixVersion.Length != 0) {
        IfixVersion = other.IfixVersion;
      }
      if (other.AssetBundleUrl.Length != 0) {
        AssetBundleUrl = other.AssetBundleUrl;
      }
      if (other.Port != 0) {
        Port = other.Port;
      }
      if (other.Ip.Length != 0) {
        Ip = other.Ip;
      }
      if (other.Msg.Length != 0) {
        Msg = other.Msg;
      }
      if (other.IfixUrl.Length != 0) {
        IfixUrl = other.IfixUrl;
      }
      if (other.MdkResVersion.Length != 0) {
        MdkResVersion = other.MdkResVersion;
      }
      if (other.ClientSecretKey.Length != 0) {
        ClientSecretKey = other.ClientSecretKey;
      }
      if (other.Unk1 != false) {
        Unk1 = other.Unk1;
      }
      if (other.Unk2 != false) {
        Unk2 = other.Unk2;
      }
      if (other.Unk3 != false) {
        Unk3 = other.Unk3;
      }
      if (other.Unk4 != false) {
        Unk4 = other.Unk4;
      }
      if (other.Unk5 != false) {
        Unk5 = other.Unk5;
      }
      if (other.Unk6 != false) {
        Unk6 = other.Unk6;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            AssetBundleUrl = input.ReadString();
            break;
          }
          case 32: {
            Unk1 = input.ReadBool();
            break;
          }
          case 56: {
            Port = input.ReadUInt32();
            break;
          }
          case 64: {
            Unk2 = input.ReadBool();
            break;
          }
          case 74: {
            ExResourceUrl = input.ReadString();
            break;
          }
          case 90: {
            LuaUrl = input.ReadString();
            break;
          }
          case 98: {
            Ip = input.ReadString();
            break;
          }
          case 106: {
            RegionName = input.ReadString();
            break;
          }
          case 528: {
            Unk3 = input.ReadBool();
            break;
          }
          case 1122: {
            IfixUrl = input.ReadString();
            break;
          }
          case 4408: {
            Unk4 = input.ReadBool();
            break;
          }
          case 4730: {
            ClientSecretKey = input.ReadString();
            break;
          }
          case 7432: {
            Unk5 = input.ReadBool();
            break;
          }
          case 7832: {
            Unk6 = input.ReadBool();
            break;
          }
          case 8610: {
            Msg = input.ReadString();
            break;
          }
          case 11554: {
            IfixVersion = input.ReadString();
            break;
          }
          case 11650: {
            MdkResVersion = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            AssetBundleUrl = input.ReadString();
            break;
          }
          case 32: {
            Unk1 = input.ReadBool();
            break;
          }
          case 56: {
            Port = input.ReadUInt32();
            break;
          }
          case 64: {
            Unk2 = input.ReadBool();
            break;
          }
          case 74: {
            ExResourceUrl = input.ReadString();
            break;
          }
          case 90: {
            LuaUrl = input.ReadString();
            break;
          }
          case 98: {
            Ip = input.ReadString();
            break;
          }
          case 106: {
            RegionName = input.ReadString();
            break;
          }
          case 528: {
            Unk3 = input.ReadBool();
            break;
          }
          case 1122: {
            IfixUrl = input.ReadString();
            break;
          }
          case 4408: {
            Unk4 = input.ReadBool();
            break;
          }
          case 4730: {
            ClientSecretKey = input.ReadString();
            break;
          }
          case 7432: {
            Unk5 = input.ReadBool();
            break;
          }
          case 7832: {
            Unk6 = input.ReadBool();
            break;
          }
          case 8610: {
            Msg = input.ReadString();
            break;
          }
          case 11554: {
            IfixVersion = input.ReadString();
            break;
          }
          case 11650: {
            MdkResVersion = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
