// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: Gateserver2100.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace sr.ParseGateway
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Gateserver : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(3, Name = @"lua_url")]
        [global::System.ComponentModel.DefaultValue("")]
        public string LuaUrl { get; set; } = "";

        [global::ProtoBuf.ProtoMember(6, Name = @"ex_resource_url")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ExResourceUrl { get; set; } = "";

        [global::ProtoBuf.ProtoMember(12, Name = @"asset_bundle_url")]
        [global::System.ComponentModel.DefaultValue("")]
        public string AssetBundleUrl { get; set; } = "";

        [global::ProtoBuf.ProtoMember(150, Name = @"ifix_url")]
        [global::System.ComponentModel.DefaultValue("")]
        public string IfixUrl { get; set; } = "";

        [global::ProtoBuf.ProtoMember(5, Name = @"region_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string RegionName { get; set; } = "";

        [global::ProtoBuf.ProtoMember(10, Name = @"ip")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Ip { get; set; } = "";

        [global::ProtoBuf.ProtoMember(1, Name = @"port")]
        public uint Port { get; set; }

        [global::ProtoBuf.ProtoMember(1836, Name = @"msg")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Msg { get; set; } = "";

        [global::ProtoBuf.ProtoMember(687, Name = @"ifix_version")]
        [global::System.ComponentModel.DefaultValue("")]
        public string IfixVersion { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2010, Name = @"mdk_res_version")]
        [global::System.ComponentModel.DefaultValue("")]
        public string MdkResVersion { get; set; } = "";

        [global::ProtoBuf.ProtoMember(605, Name = @"client_secret_key")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ClientSecretKey { get; set; } = "";

        [global::ProtoBuf.ProtoMember(7, Name = @"unk1")]
        public bool Unk1 { get; set; }

        [global::ProtoBuf.ProtoMember(11, Name = @"unk2")]
        public bool Unk2 { get; set; }

        [global::ProtoBuf.ProtoMember(960, Name = @"unk3")]
        public bool Unk3 { get; set; }

        [global::ProtoBuf.ProtoMember(1120, Name = @"unk4")]
        public bool Unk4 { get; set; }

        [global::ProtoBuf.ProtoMember(1362, Name = @"unk5")]
        public bool Unk5 { get; set; }

        [global::ProtoBuf.ProtoMember(1906, Name = @"unk6")]
        public bool Unk6 { get; set; }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
